# Generated by Django 5.2.1 on 2026-06-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(default='home', max_length=20),
            preserve_default=False,
        ),
    ]
