# Generated by Django 5.2.1 on 2026-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagecontent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(max_length=20),
        ),
    ]
