# Generated by Django 5.2.1 on 2026-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pagecontent_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/')),
                ('alt_text', models.CharField(default='Iste Sahne Logo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
